version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_drupal
      - MARIADB_DATABASE=bitnami_drupal
    volumes:
      - 'mariadb_data:/bitnami'
  drupal:
    image: 'bitnami/drupal:8'
    labels:
      kompose.service.type: nodeport
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=bn_drupal
      - DRUPAL_DATABASE_NAME=bitnami_drupal
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8081:80'
      - '443:443'
    volumes:
      - '${WEBAPP_STORAGE_HOME}/modules:/opt/bitnami/drupal/modules'
      - '${WEBAPP_STORAGE_HOME}/profiles:/opt/bitnami/drupal/profiles'
      - '${WEBAPP_STORAGE_HOME}/themes:/opt/bitnami/drupal/themes'
      - '${WEBAPP_STORAGE_HOME}/sites:/opt/bitnami/drupal/sites'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  drupal_data:
    driver: local